// Generated by dts-bundle v0.7.3
// Dependencies for this module:
//   ../dat.gui
//   ../@graspologic/renderer

declare module '@graspologic/render-controls' {
    export * from '@graspologic/render-controls/configSections';
}

declare module '@graspologic/render-controls/configSections' {
    export * from '@graspologic/render-controls/configSections/attachDisplaySettings';
    export * from '@graspologic/render-controls/configSections/attachEdgeSettings';
    export * from '@graspologic/render-controls/configSections/attachNodeSettings';
}

declare module '@graspologic/render-controls/configSections/attachDisplaySettings' {
    import { GUI } from 'dat.gui';
    import { GraphRenderer } from '@graspologic/renderer';
    export interface DisplaySettingsConfig {
            interpolationTimeRange: [number, number];
    }
    /**
        * @internal
        *
        * Attaches the "Display" settings to the given dat.gui instance for the given graph renderer
        * @param gui The GUI instance
        * @param renderer The graph renderer
        */
    export function attachDisplaySettings(gui: GUI, renderer: GraphRenderer, { interpolationTimeRange, }?: Partial<DisplaySettingsConfig>): () => void;
}

declare module '@graspologic/render-controls/configSections/attachEdgeSettings' {
    import { GUI } from 'dat.gui';
    import { GraphRenderer } from '@graspologic/renderer';
    export interface EdgeSettingsConfig {
            alphaRange: [number, number];
            minWidthRange: [number, number];
            maxWidthRange: [number, number];
    }
    /**
        * @internal
        *
        * Attaches the "Edge" settings to the given dat.gui instance for the given graph renderer
        * @param gui The GUI instance
        * @param renderer The graph renderer
        */
    export function attachEdgeSettings(gui: GUI, renderer: GraphRenderer, { alphaRange, minWidthRange, maxWidthRange, }?: Partial<EdgeSettingsConfig>): () => void;
}

declare module '@graspologic/render-controls/configSections/attachNodeSettings' {
    import { GUI } from 'dat.gui';
    import { GraphRenderer } from '@graspologic/renderer';
    export interface NodeSettingsConfig {
            minRadiusRange: [number, number];
            maxRadiusRange: [number, number];
    }
    /**
        * @internal
        *
        * Attaches the "Node" settings to the given dat.gui instance for the given graph renderer
        * @param gui The GUI instance
        * @param renderer The graph renderer
        */
    export function attachNodeSettings(gui: GUI, renderer: GraphRenderer, { minRadiusRange, maxRadiusRange, }?: Partial<NodeSettingsConfig>): () => void;
}

