plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: '@yarnpkg/plugin-version'
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

yarnPath: .yarn/releases/yarn-3.1.0.cjs

changesetIgnorePatterns:
  - '**/*.spec.{js,ts,tsx}'

packageExtensions:
  '@chart-parts/react@*':
    peerDependencies:
      'rxjs': '*'
  'styled-components@*':
    dependencies:
      'react-is': '^16'
  '@essex/webpack-config@*':
    peerDependencies:
      'raw-loader': '*'
      'worker-loader': '*'
  '@essex/storybook-config@*':
    peerDependencies:
      'raw-loader': '*'
      'worker-loader': '*'
  '@storybook/addon-knobs@*':
    peerDependencies:
      '@storybook/client-api': '*'
      '@storybook/core-events': '*'
  '@storybook/builder-webpack4@*':
    peerDependencies:
      'worker-loader': '*'
      'webpack-glsl-loader': '*'
  '@storybook/core-server@*':
    peerDependencies:
      'worker-loader': '*'
      'webpack-glsl-loader': '*'
  '@storybook/core@*':
    peerDependencies:
      'worker-loader': '*'
      'webpack-glsl-loader': '*'
  '@storybook/react@*':
    peerDependencies:
      'worker-loader': '*'
      'webpack-glsl-loader': '*'
