changesetIgnorePatterns:
  - '**/*.spec.{js,ts,tsx}'

packageExtensions:
  '@chart-parts/react@*':
    peerDependencies:
      rxjs: '*'
  '@essex/storybook-config@*':
    peerDependencies:
      raw-loader: '*'
      worker-loader: '*'
  '@essex/webpack-config@*':
    peerDependencies:
      raw-loader: '*'
      worker-loader: '*'
  '@storybook/addon-knobs@*':
    peerDependencies:
      '@storybook/client-api': '*'
      '@storybook/core-events': '*'
  '@storybook/builder-webpack4@*':
    peerDependencies:
      webpack-glsl-loader: '*'
      worker-loader: '*'
  '@storybook/core-server@*':
    peerDependencies:
      webpack-glsl-loader: '*'
      worker-loader: '*'
  '@storybook/core@*':
    peerDependencies:
      webpack-glsl-loader: '*'
      worker-loader: '*'
  '@storybook/react@*':
    peerDependencies:
      webpack-glsl-loader: '*'
      worker-loader: '*'
  styled-components@*:
    dependencies:
      react-is: ^16

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: '@yarnpkg/plugin-version'
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

yarnPath: .yarn/releases/yarn-3.1.1.cjs
npmAuthToken: '${NPM_AUTH_TOKEN-emptytoken}'
#npmRegistryServer: 'https://registry.npmjs.com'