changesetIgnorePatterns:
  - '**/*.spec.{js,ts,tsx}'

compressionLevel: mixed

enableGlobalCache: false

packageExtensions:
  '@chart-parts/react@*':
    peerDependencies:
      rxjs: '*'
  '@essex/storybook-config@*':
    peerDependencies:
      raw-loader: '*'
      worker-loader: '*'
  '@essex/webpack-config@*':
    peerDependencies:
      raw-loader: '*'
      worker-loader: '*'
  '@storybook/addon-knobs@*':
    peerDependencies:
      '@storybook/client-api': '*'
      '@storybook/core-events': '*'
  '@storybook/builder-webpack4@*':
    peerDependencies:
      webpack-glsl-loader: '*'
      worker-loader: '*'
  '@storybook/core-server@*':
    peerDependencies:
      webpack-glsl-loader: '*'
      worker-loader: '*'
  '@storybook/core@*':
    peerDependencies:
      webpack-glsl-loader: '*'
      worker-loader: '*'
  '@storybook/react@*':
    peerDependencies:
      webpack-glsl-loader: '*'
      worker-loader: '*'
  styled-components@*:
    dependencies:
      react-is: ^16

yarnPath: .yarn/releases/yarn-4.0.0-rc.50.cjs
