// Generated by dts-bundle v0.7.3
// Dependencies for this module:
//   ../react

declare module '@graspologic/render-controls-react' {
    export * from '@graspologic/render-controls-react/components';
    export * from '@graspologic/render-controls-react/context';
}

declare module '@graspologic/render-controls-react/components' {
    export * from '@graspologic/render-controls-react/components/DisplaySettings';
    export * from '@graspologic/render-controls-react/components/EdgeSettings';
    export * from '@graspologic/render-controls-react/components/NodeSettings';
    export * from '@graspologic/render-controls-react/components/SettingsPane';
}

declare module '@graspologic/render-controls-react/context' {
    /**
      * @internal
      *
      * The dat.gui context
      */
    export const DatGuiContext: any;
}

declare module '@graspologic/render-controls-react/components/DisplaySettings' {
    import * as React from 'react';
    export interface DisplaySettingsProps {
            interpolationTimeRange?: [number, number];
    }
    /**
        * Attaches the graph renderer display settings to the SettingsPane
        */
    export const DisplaySettings: React.FC<DisplaySettingsProps>;
}

declare module '@graspologic/render-controls-react/components/EdgeSettings' {
    import * as React from 'react';
    export interface EdgeSettingsProps {
            alphaRange?: [number, number];
            minWidthRange?: [number, number];
            maxWidthRange?: [number, number];
    }
    /**
        * Attaches the graph renderer edge settings to the SettingsPane
        */
    export const EdgeSettings: React.FC<EdgeSettingsProps>;
}

declare module '@graspologic/render-controls-react/components/NodeSettings' {
    import * as React from 'react';
    export interface NodeSettingsProps {
            /**
                * The range of values to allow for the min-radius settings
                */
            minRadiusRange?: [number, number];
            /**
                * The range of values to allow for the max-radius settings
                */
            maxRadiusRange?: [number, number];
    }
    /**
        * Attaches the graph renderer node settings to the SettingsPane
        */
    export const NodeSettings: React.FC<NodeSettingsProps>;
}

declare module '@graspologic/render-controls-react/components/SettingsPane' {
    import * as React from 'react';
    /**
        * The SettingsPane props
        */
    export interface SettingsPaneProps {
            /**
                * The classname to attach to the settings pane
                */
            className?: string;
            /**
                * The styles to apply to the settings pane
                */
            style?: React.CSSProperties;
            /**
                * The width of the settings pane
                */
            guiWidth?: number;
    }
    /**
        * Attaches a settings pane to the GraphView component
        */
    export const SettingsPane: React.FC<SettingsPaneProps>;
}

