name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
      - uses: actions/checkout@v1

      - name: Debug Action
        uses: hmarr/debug-action@v1.0.0

      - name: Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          always-auth: true
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org
          scope: '@graspologic'
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - run: npm i -g pnpm
        name: Install pnpm

      - run: pnpm install
        name: Install Dependencies

      - run: pnpm ci
        name: Execute Tests
        env:
          CI: true

      - if: ${{ github.event_name == 'push' && matrix.node-version == '12.x' }}
        run: pnpm release -- --tag "beta.${{ github.run_number }}" --git-checks false
        name: Publish to npm
